language: python

python:
- "2.7"

before_install:
- sudo apt-get install -y closure-compiler nodejs npm
- sudo npm install -g jshint

install:
- pip install cheetah
- pip install twisted
- pip install pyopenssl
- pip install bandit
- pip install flake8

script: 
- python -m compileall -l . -l plugin -l plugin/backport -l plugin/controllers -l plugin/controllers/models
- cheetah compile -R plugin
- python testsuite/evil_eval.py

after_success:
- bandit -r plugin -f html -o bandit.html
- python -m flake8 --ignore=W191,E501 plugin/ --output-file flake8_report.txt
- jshint ./sourcefiles/js/ | tee jshint1_report.txt
- jshint ./sourcefiles/themes/absb/js/ | tee jshint2_report.txt
- ./create_ipk.sh
- export PKG=$(ls -1 *.ipk)
- mkdir Rel
- mv "${PKG}" ./Rel
- mv bandit.html ./Rel
- mv flake8_report.txt ./Rel
- mv jshint1_report.txt ./Rel
- mv jshint2_report.txt ./Rel

deploy:
  provider: pages
  local_dir: Rel
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  target_branch: gh-pages
  edge:
    branch: v1.8.47
  on:
    branch: master
    